name: CI with Custom Docker Image for eslint and terraform deployment

on:
  push:
    branches:
      - feature-512-deploy-backend
  pull_request:
    branches:
      - feature-512-deploy-backend

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies in backend
        run: npm install
        working-directory: ./backend

      - name: Lint check in backend
        run: npm run lint
        working-directory: ./backend

  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/6-great-leaders/iot_backend/backend:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Init terraform
        run: terraform init
        working-directory: ./infra

