name: Format Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies in database
        run: npm install
        working-directory: ./database

      - name: Install dependencies in backend
        run: npm install
        working-directory: ./backend

      - name: Lint check in database
        run: npm run lint
        working-directory: ./database

      - name: Lint check in backend
        run: npm run lint
        working-directory: ./backend
